apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-server
  labels:
    app: fastify_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastify_server
  template:
    metadata:
      labels:
        app: fastify_server
    spec:
      containers:
        - name: fastify-server
          image: gkabitakis/fastify-server:1.0.0
          # resources:
          #   requests:
          #     memory: '64Mi'
          #     cpu: '250m'
          #   limits:
          #     memory: '128Mi'
          #     cpu: '500m'
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-server
  namespace: fastify-server
spec:
  selector:
    app: fastify_server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
