apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-server
  namespace: fastify-server
  labels:
    app: fastify_server
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: '5%'
  selector:
    matchLabels:
      app: fastify_server
  template:
    metadata:
      labels:
        app: fastify_server
    spec:
      nodeSelector:
        prefer: fastify-server
      tolerations:
        - key: 'special'
          operator: 'Equal'
          value: 'fastify-server'
          effect: 'NoExecute'
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 100
      #         preference:
      #           matchExpressions:
      #             - key: prefer
      #               operator: In
      #               values:
      #                 - fastify-server
      containers:
        - name: fastify-server
          image: gkabitakis/fastify-server:1.0.0
          resources:
            requests:
              memory: '250Mi'
              cpu: '0.2'
            limits:
              memory: '300Mi'
              cpu: '0.4'
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-server
  namespace: fastify-server
spec:
  selector:
    app: fastify_server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
