apiVersion: v1
kind: Pod
metadata:
  namespace: fastify-server
  name: node-box
  labels:
    app: nodeBox
spec:
  nodeSelector:
    node.type: master
  containers:
    - name: node-box
      image: node
      resources:
        requests:
          memory: '500Mi'
          cpu: '1'
        limits:
          memory: '1Gi'
          cpu: '2'
      command: ["sh", "-c", "tail -f /dev/null"]

# npm i autocannon -g 
# echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null
# apt-get update
# apt-get -y install curl