apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-server
  name: go-server
  labels:
    app: go_server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go_server
  template:
    metadata:
      labels:
        app: go_server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.type
                    operator: In
                    values:
                      - slave
      containers:
        - name: go-server
          image: gkabitakis/go-server:1.0.0
          resources:
            requests:
              memory: '250Mi'
              cpu: '0.2'
            limits:
              memory: '300Mi'
              cpu: '0.4'
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: go-server
spec:
  selector:
    app: go_server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
