apiVersion: v1
kind: Pod
metadata:
  namespace: go-server
  name: node-box
  labels:
    app: nodeBox
spec:
  containers:
    - name: node-box
      image: node
      command: ["sh", "-c", "tail -f /dev/null"]

# npm i autocannon -g 
# echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null
# apt-get update
# apt-get -y install curl